# Day 2 

## For Loop 

In [1]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
for i in range(0, 10 ,2):
    print(i)

0
2
4
6
8


In [4]:
for i in range(10, 1, -1):
    print(i)

10
9
8
7
6
5
4
3
2


In [5]:
a = [10,9,1,2,3,4,5,6,9]

In [6]:
len(a)

9

In [7]:
for i in a:
    print(i, end = " ")

10 9 1 2 3 4 5 6 9 

In [8]:
for i in range(a):
    print(i)

TypeError: 'list' object cannot be interpreted as an integer

In [9]:
for i in range(len(a)):
    print(i + 1 , end = " ")

1 2 3 4 5 6 7 8 9 

## While Loop 

In [10]:
z = 0

In [11]:
while z < 10:
    if z == 5:
        break
    print(z)
    z = z + 1

0
1
2
3
4


In [12]:
a = 0 

In [13]:
while True:
    if a == 10:
        break
    print(a)
    a += 1 # => a = a + 1
    # a -= 1 # => a = a -1 

0
1
2
3
4
5
6
7
8
9


In [14]:
for i in range(20):
    print(i, end = " ")
    i += 5 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [15]:
 i = 20

In [16]:
while i > 0:
    if i > 20:
        break
    print(i, end = " ")
    i -= 2

20 18 16 14 12 10 8 6 4 2 

# Data science part Begins 

In [19]:
import numpy as np

In [20]:
array1 = np.array([1,2,3,4,5])

In [21]:
type(array1)

numpy.ndarray

In [22]:
array2 = np.array([1,2,3,4,5])

In [23]:
array2

array([1, 2, 3, 4, 5])

In [24]:
array1

array([1, 2, 3, 4, 5])

In [25]:
array1 + array2

array([ 2,  4,  6,  8, 10])

In [27]:
a = np.array([1,2,3])

b = np.array([
                [1,2,3],
                [4,5,6]
            ])

In [28]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [29]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [30]:
b.ndim

2

In [31]:
b.shape

(2, 3)

In [32]:
a.shape

(3,)

In [33]:
b.size

6

In [34]:
a.size

3

In [35]:
b[ 1:, 1:]

array([[5, 6]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
c = np.full((3,3), 1)

In [39]:
c.dtype

dtype('int32')

In [40]:
a,b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [41]:
np.add(a, b)

array([[2, 4, 6],
       [5, 7, 9]])

In [42]:
np.subtract(a, b)

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [43]:
np.multiply(a, b)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [44]:
np.divide(a, b)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [45]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.arange(1, 10, 5)

array([1, 6])

In [47]:
example_list = []

for i in range(100000):
    example_list.append(i)

In [48]:
numpy_example_list = np.arange(0, 100000)

In [58]:
type(numpy_example_list), type(example_list)

(numpy.ndarray, list)

In [59]:
%timeit sum(example_list)

3.87 ms ± 493 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [67]:
%timeit np.sum(numpy_example_list)

99.4 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [68]:
np.sqrt(25)

5.0

In [69]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [70]:
a < b

array([[False, False, False],
       [ True,  True,  True]])

## Random Number in numpy 

In [71]:
np.random.seed(1)
np.random.randint(1,15, size = (5,5))

array([[ 6, 12, 13,  9, 10],
       [12,  6,  1,  1,  2],
       [13,  8, 14, 13,  7],
       [10,  3,  5,  6,  3],
       [ 5, 12, 13, 11, 13]])

In [72]:
np.random.seed(5)
np.random.random(size=(5,5))

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

## Slicing in numpy n - dim arrays! 

In [75]:
ndim_array_example = np.random.randint(1,15, size = (3,3))

In [76]:
ndim_array_example

array([[ 5,  5, 10],
       [ 4, 12,  3],
       [ 5,  7, 10]])

In [77]:
ndim_array_example[ 2: , 1:2]

array([[7]])

In [78]:
ndim_array_example[ 2:3, 1:]

array([[ 7, 10]])

In [79]:
ndim_array_example[ 1:2, 2:3] + ndim_array_example[ 1:2, 0:1]

array([[7]])

## Reshaping the array 

In [80]:
a

array([1, 2, 3])

In [81]:
a.shape

(3,)

In [82]:
a = a.reshape((1,3))

In [83]:
a.shape

(1, 3)

In [84]:
a

array([[1, 2, 3]])

In [85]:
a, b

(array([[1, 2, 3]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [86]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [87]:
a1 = np.random.randint(1, 3, size = (2,2))

In [88]:
a1

array([[2, 2],
       [1, 2]])

In [89]:
a = 5
b = 6

In [90]:
a, b

(5, 6)

In [91]:
a, b = b, a

In [92]:
a, b

(6, 5)

In [93]:
a1, b1 = np.random.randint(1,3, size = (2,5)), np.random.randint(1,3, size = (2,5))

In [94]:
a1, b1

(array([[2, 2, 1, 1, 2],
        [1, 1, 2, 2, 2]]),
 array([[1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2]]))

In [95]:
a1.dot(b1)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [96]:
a1.shape

(2, 5)

In [97]:
b1.shape

(2, 5)

In [98]:
a1.dot(b1.reshape(5,2))

array([[14, 15],
       [15, 14]])

In [99]:
a1.dot(b1.T)

array([[14, 14],
       [15, 15]])

In [103]:
b1.T

array([[1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [104]:
b1.reshape((5,2))

array([[1, 2],
       [2, 2],
       [2, 1],
       [2, 2],
       [2, 2]])

In [105]:
b1

array([[1, 2, 2, 2, 2],
       [1, 2, 2, 2, 2]])

## sorting an array 

In [106]:
a1.sort()

In [107]:
a1

array([[1, 1, 2, 2, 2],
       [1, 1, 2, 2, 2]])

## Data Loading using numpy

In [110]:
data = np.loadtxt("rp.txt", dtype = "str", delimiter = " ,")

OSError: rp.txt not found.

In [109]:
data

NameError: name 'data' is not defined

# Pandas 

In [ ]:
import pandas as pd

## series data types in Pandas

In [ ]:
example_pandas_series = pd.Series(["Data", "science", 'Training'])

In [ ]:
type(example_pandas_series)

In [ ]:
example_pandas_series1 = pd.Series(["Data", "Science", " Training", index = ["D", " S", "T"]])

In [ ]:
example_pandas_series1

In [ ]:
type(example_pandas_series1)

In [ ]:
colours = pd.Series(["Red", "Green", "Yellow"])
cars = pd.Series(["Lambo", "Audi", "BMW"])

## DataFrames Data types in pandas 

In [ ]:
example_dataframe = pd.Dataframe([1,2,3,4,5], index = ["1", "2", "3", "4", "5"])

In [ ]:
exxample_dataframe

In [ ]:
example_dataframe1 = pd.DataFrame({"colour" : colours, "Cars" : cars})

In [ ]:
example_dataframe2